@echo off
REM Kokoro TTS Installation Script for Windows
REM This script installs Kokoro TTS outside the main Walls project directory
REM to keep the repository clean and avoid licensing issues

setlocal enabledelayedexpansion

REM Configuration
set "WALLS_DIR=%~dp0"

echo Kokoro TTS Installation Script
echo ================================
echo.
echo This script will install Kokoro TTS via pip
echo Walls project directory: %WALLS_DIR%
echo.

REM Check if git is installed
git --version >nul 2>&1
if errorlevel 1 (
    echo Error: git is not installed. Please install git first.
    pause
    exit /b 1
)

REM Check if Python is installed
python --version >nul 2>&1
if errorlevel 1 (
    echo Error: Python is not installed. Please install Python first.
    pause
    exit /b 1
)

REM Check if Kokoro is already installed
python -m pip show kokoro >nul 2>&1
if %errorlevel% equ 0 (
    echo WARNING: Kokoro is already installed
    set /p "REPLY=Do you want to reinstall? (y/N): "
    if /i not "!REPLY!"=="y" (
        echo Installation cancelled.
        pause
        exit /b 0
    )
)

REM Install Kokoro TTS
echo Installing Kokoro TTS via pip...
python -m pip install "kokoro>=0.9.4"
if errorlevel 1 (
    echo ERROR: Failed to install Kokoro via pip
    pause
    exit /b 1
)

REM Install additional dependencies
echo Installing additional dependencies...
python -m pip install soundfile
if errorlevel 1 (
    echo Warning: Some dependencies may not have installed correctly.
)

echo Kokoro TTS installed successfully!

REM Create configuration file
echo Creating configuration file...

REM Create voice_mode directory if it doesn't exist
if not exist "%WALLS_DIR%ai_interface\voice_mode" mkdir "%WALLS_DIR%ai_interface\voice_mode"

set "CONFIG_FILE=%WALLS_DIR%ai_interface\voice_mode\kokoro_config.py"

(
echo """Kokoro TTS Configuration
echo.
echo This file is automatically generated by the Kokoro installer.
echo Kokoro TTS is installed via pip and should be available system-wide.
echo """
echo.
echo # Kokoro is installed via pip, no additional path configuration needed
echo KOKORO_INSTALLED_VIA_PIP = True
echo.
echo try:
echo     import kokoro
echo     KOKORO_AVAILABLE = True
echo except ImportError:
echo     KOKORO_AVAILABLE = False
echo     print^("Warning: Kokoro not found. Please run: pip install kokoro^>=0.9.4"^)
) > "%CONFIG_FILE%"

echo Configuration file created at %CONFIG_FILE%

REM Test installation
echo Testing Kokoro TTS installation...

python -c "try: import kokoro; from kokoro import KPipeline; print('Testing basic Kokoro functionality...'); pipeline = KPipeline(lang_code='a'); print('Kokoro installation verified!'); print('KPipeline can be initialized successfully'); except ImportError as e: print(f'Kokoro import failed: {e}'); print('Please run: pip install kokoro>=0.9.4'); exit(1); except Exception as e: print(f'Installation test failed: {e}'); exit(1)" 2>nul
if %errorlevel% equ 0 (
    echo Kokoro installation test passed!
) else (
    echo ERROR: Kokoro installation test failed
)

REM Show usage instructions
echo.
echo Installation completed!
echo.
echo Kokoro TTS has been installed via pip
echo Configuration file created at: %CONFIG_FILE%
echo.
echo Next steps:
echo 1. Test the voice mode in your Walls application
echo 2. Kokoro models will be downloaded automatically when first used
echo 3. The installation is system-wide and available to all Python environments
echo.
echo To uninstall Kokoro TTS:
echo   pip uninstall kokoro
echo   del "%CONFIG_FILE%"
echo.

pause